.TH PASSGEN 1 "January 2026" "passgen" "User Commands"

.SH NAME
passgen \- generate a random password.

.SH SYNOPSIS
.B passgen
.RI [ options ]

.SH DESCRIPTION
\fBpassgen\fR is a command-line utility that generates random passwords based on user-defined criteria.
It allows users to specify the length of the password and whether to include letters, digits, and symbols.

.SH OPTIONS
.TP
.B \-l, \--length
Specify the length of the password. This option is required and must be a positive integer.

.TP
.B \-a, \--letters
Include letters (both uppercase and lowercase) in the generated password.

.TP
.B \-d, \--digits
Include digits (0-9) in the generated password.

.TP
.B \-s, \--symbols
Include symbols (e.g., !@#$%^&*-=_+) in the generated password.

.TP
.B \-o, \--save-to
Specify a file to save the generated password. If this option is not provided, the password will be printed to the standard output.

.SH EXAMPLES
.TP
.B passgen -l 12 -a -d -s
Generate a 12-character password that includes letters, digits, and symbols.

.TP
.B passgen -l 16 -a -d
Generate a 16-character password that includes letters and digits only.

.TP
.B passgen -l 8 -s -o password.txt
Generate an 8-character password that includes symbols and save it to 'password.txt'.

.SH AUTHORS
Currently maintained by Kinderfeld <https://github.com/Kinderfeld>

.SH COPYRIGHT
Copyright (c) 2025-2026 Archetypum.

Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions
and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of
conditions and the following disclaimer in the documentation and/or other materials provided

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

.SH REPORTING BUGS
Project homepage: <https://github.com/Archetypum/passgen>

