#!/usr/bin/env python3
#
# `passgen` - free password generation utility, made by Archetypum.
#
# Copyright (c) 2025-2026 Archetypum.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted
# provided that the following conditions are met:
# 
#   1. Redistributions of source code must retain the above copyright notice, this list of conditions
#   and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright notice, this list of
#   conditions and the following disclaimer in the documentation and/or other materials provided
#   with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import string
import typing
import secrets
import argparse


def generate_password(length: int, use_letters: bool, use_digits: bool, use_symbols: bool) -> str:
    characters: str = ""

    if use_letters:
        characters += string.ascii_letters
    if use_digits:
        characters += string.digits
    if use_symbols:
        characters += "!@#$%^&*-=_+"

    if not characters:
        raise ValueError("[!] At least one character type must be selected.")

    return "".join(secrets.choice(characters) for _ in range(length))


def main(passgen_version: str) -> typing.NoReturn:
    parser = argparse.ArgumentParser(description="Generate a random password.")
    parser.add_argument("--version", "-v", action="store_true", help="Show version.")
    parser.add_argument("--length", "-l", type=int, help="Length of the password.")
    parser.add_argument("--letters", "-a", action="store_true", help="Include letters in the password.")
    parser.add_argument("--digits", "-d", action="store_true", help="Include digits in the password.")
    parser.add_argument("--symbols", "-s", action="store_true", help="Include symbols in the password.")
    parser.add_argument("--save-to", "-o", type=str, help="File to save the generated password.")

    args = parser.parse_args()

    if args.version:
        print(passgen_version)
        return

    if args.length is None or args.length <= 0:
        print("[!] Error: Length must be a positive integer.")
        return

    try:
        password: str = generate_password(args.length, args.letters, args.digits, args.symbols)
        print(password)

        if args.save_to:
            with open(args.save_to, "w") as password_file:
                password_file.write(password)

    except ValueError as error:
        print(f"[!] Error: {error}")


if __name__ == "__main__":
    version: str = "v3"

    main(version)

