#!/usr/bin/env python3
#
# `passgen` - free password generation utility, made by Archetypum.
#
# Copyright (C) 2025 Archetypum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>

import string
import typing
import secrets
import argparse


def generate_password(length: int, use_letters: bool, use_digits: bool, use_symbols: bool) -> str:
    characters: str = ""

    if use_letters:
        characters += string.ascii_letters
    if use_digits:
        characters += string.digits
    if use_symbols:
        characters += "!@#$%^&*-=_+"

    if not characters:
        raise ValueError("[!] At least one character type must be selected.")

    return "".join(secrets.choice(characters) for _ in range(length))


def main(passgen_version: str) -> typing.NoReturn:
    parser = argparse.ArgumentParser(description="Generate a random password.")
    parser.add_argument("--version", "-v", action="store_true", help="Show version.")
    parser.add_argument("--length", "-l", type=int, help="Length of the password.")
    parser.add_argument("--letters", "-a", action="store_true", help="Include letters in the password.")
    parser.add_argument("--digits", "-d", action="store_true", help="Include digits in the password.")
    parser.add_argument("--symbols", "-s", action="store_true", help="Include symbols in the password.")
    parser.add_argument("--save-to", "-o", type=str, help="File to save the generated password.")

    args = parser.parse_args()

    if args.version:
        print(f"[*] passgen version: {passgen_version}")
        return

    if args.length is None or args.length <= 0:
        print("[!] Error: Length must be a positive integer.")
        return

    try:
        password: str = generate_password(args.length, args.letters, args.digits, args.symbols)
        print(f"[*] Generated password: {password}")

        if args.save_to:
            with open(args.save_to, "w") as password_file:
                password_file.write(password)
            print(f"[*] Password saved to '{args.save_to}'")

    except ValueError as error:
        print(f"[!] Error: {error}")


if __name__ == "__main__":
    version: str = "v0.0.2"

    main(version)

